// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject1
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIXProject1.54ae2c46-c1a2-4075-addd-b218725a6525";
        public const string Name = "SnakeToCamelCase";
        public const string Description = @"Convert snake case convert to camel case ";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Ali ihsan AKAY";
        public const string Tags = "";
    }
}
